"""
Active Objects Manager module for tracking and managing object lifecycles.

This module provides the ActiveObjectsManager class which tracks active objects
using weak references to monitor memory usage and object lifecycle without
preventing garbage collection.
"""

import logging
import threading
import weakref
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Dict, Optional

from smartpool.core.data_models import PooledObject
from smartpool.core.utils import safe_log

if TYPE_CHECKING:  # pragma: no cover
    from smartpool.core.smartpool_manager import SmartObjectManager


@dataclass
class ActiveObjectInfo:
    """
    Represents detailed information about an object currently
    being tracked by the ActiveObjectsManager.

    Attributes:
        key (str): A unique identifier for the type or category of the object,
                typically generated by the factory.
        estimated_size (int): The estimated memory size of the object in bytes.
        created_at (float): The timestamp (Unix epoch) when the object was created.
        access_count (int): The number of times the object has been accessed
                or acquired from the pool.
    """

    key: str
    estimated_size: int
    created_at: float
    access_count: int


class ActiveObjectsManager:
    """
    Manages the lifecycle and tracking of active objects (objects currently in use outside the pool)
    using weak references. This ensures that the pool does not prevent objects from being garbage
    collected when they are no longer referenced by the application, while still allowing the pool
    to monitor their status and collect statistics.

    Responsibilities:
    - Tracking active objects with WeakRefs to monitor their existence without strong references.
    - Managing cleanup callbacks for objects that are garbage collected.
    - Providing statistics on active objects, including their count and memory usage.
    """

    def __init__(self, pool: "SmartObjectManager"):
        """
        Initializes the ActiveObjectsManager.

        Args:
            pool (SmartObjectManager): A reference to the main memory pool, used for logging and
                                      accessing shared resources like the logger.
        """
        self.pool = pool
        self.logger = logging.getLogger(__name__)

        # Dictionary to store weak references to active objects, keyed by their unique ID.
        self._active_objects_count: Dict[int, Optional[weakref.ref[Any]]] = {}
        # Dictionary to store metadata about active objects, keyed by their unique ID.
        self._active_objects_count_info: Dict[int, ActiveObjectInfo] = {}
        # Counter for generating unique IDs for new active objects.
        self._next_id = 0
        # Reentrant lock for thread-safe access to shared data structures.
        self._lock = threading.RLock()

    # pylint: disable=too-many-arguments,too-many-positional-arguments
    def track_active_object(
        self, obj: PooledObject, key: str, estimated_size: int, created_at: float, access_count: int
    ) -> int:
        """
        Registers an object as active, tracking it with a weak reference and storing its metadata.
        This method is called when an object is acquired from the pool
        and is now in use by the application.

        Args:
            obj (any): The object to track.
            key (str): The unique key associated with the object's type or category.
            estimated_size (int): The estimated memory size of the object in bytes.
            created_at (float): The timestamp when the object was created.
            access_count (int): The current access count of the object.

        Returns:
            int: A unique ID assigned to the tracked object, which can be used for untracking.
        """
        with self._lock:
            obj_id = self._next_id
            self._next_id += 1

            # Some builtins (e.g. dict/list) are not weak-referenceable.
            # In that case we still track metadata and rely on explicit release().
            try:
                weak_obj = weakref.ref(obj, lambda ref: self._weakref_cleanup_callback(ref, obj_id))
                self._active_objects_count[obj_id] = weak_obj
            except TypeError:
                self._active_objects_count[obj_id] = None
                safe_log(
                    self.logger,
                    logging.DEBUG,
                    f"Object {obj_id} is not weakref-compatible; tracking without callback.",
                )

            # Store metadata
            self._active_objects_count_info[obj_id] = ActiveObjectInfo(
                key=key,
                estimated_size=estimated_size,
                created_at=created_at,
                access_count=access_count,
            )

            return obj_id

    def untrack_active_object(self, obj_id: int) -> bool:
        """
        Removes an object from active tracking. This method is typically called when an object
        is released back to the pool or explicitly destroyed.

        Args:
            obj_id (int): The unique ID of the object to untrack.

        Returns:
            bool: True if the object was successfully untracked (i.e., it was being tracked),
                  False otherwise.
        """
        with self._lock:
            removed = False

            if obj_id in self._active_objects_count:
                del self._active_objects_count[obj_id]
                removed = True

            if obj_id in self._active_objects_count_info:
                del self._active_objects_count_info[obj_id]
                removed = True

            return removed

    def get_active_count(self) -> int:
        """
        Returns the current number of active (living) objects being tracked.
        An object is considered "living" if its weak reference still points to an existing object.

        Returns:
            int: The count of living active objects.
        """
        with self._lock:
            return sum(
                1
                for weak_obj in self._active_objects_count.values()
                if weak_obj is None or weak_obj() is not None
            )

    def get_active_objects_count_info(self) -> Dict[int, ActiveObjectInfo]:
        """
        Retrieves a copy of the metadata for all currently living active objects.

        Returns:
            Dict[int, ActiveObjectInfo]: A dictionary where keys are object IDs and values are
                                        `ActiveObjectInfo` dataclass instances for living objects.
        """
        with self._lock:
            # Filter for still living objects
            living_objects = {}
            for obj_id, obj_info in self._active_objects_count_info.items():
                weak_obj = self._active_objects_count.get(obj_id)
                if weak_obj is not None and weak_obj() is None:
                    continue
                if obj_id in self._active_objects_count:
                    living_objects[obj_id] = obj_info
            return living_objects.copy()

    def cleanup_dead_weakrefs(self) -> int:
        """
        Scans through the tracked objects and removes entries for which the underlying object
        has been garbage collected (i.e., their weak reference is "dead").

        Returns:
            int: The number of dead weak references that were cleaned up.
        """
        with self._lock:
            dead_ids = []

            for obj_id, weak_obj in self._active_objects_count.items():
                if weak_obj is not None and weak_obj() is None:  # Object collected by GC
                    dead_ids.append(obj_id)

            for obj_id in dead_ids:
                self.untrack_active_object(obj_id)

            if dead_ids:
                safe_log(self.logger, logging.DEBUG, f"Cleaned up {len(dead_ids)} dead weakrefs")

            return len(dead_ids)

    def get_memory_usage_by_key(self) -> Dict[str, Dict[str, int]]:
        """
        Calculates the aggregated memory usage and count of living active objects,
        grouped by their key.

        Returns:
            Dict[str, Dict[str, int]]: A dictionary where keys are object keys (categories), and
                                    values are dictionaries containing 'count' (number of objects)
                                    and 'memory' (total estimated memory in bytes) for that key.
        """
        with self._lock:
            usage = {}

            for obj_id, obj_info in self._active_objects_count_info.items():
                # Check if object is still alive
                weak_obj = self._active_objects_count.get(obj_id)
                if weak_obj is not None and weak_obj() is None:
                    continue
                if obj_id in self._active_objects_count:
                    key = obj_info.key
                    if key not in usage:
                        usage[key] = {"count": 0, "memory": 0}

                    usage[key]["count"] += 1
                    usage[key]["memory"] += obj_info.estimated_size

            return usage

    def _weakref_cleanup_callback(self, _ref: weakref.ref, obj_id: int) -> None:
        """
        Callback function executed when an object tracked by a weak reference is garbage collected.
        This indicates that an active object was released by the application without being
        explicitly untracked by the pool (e.g., not returned to the pool).

        Args:
            obj_id (int): The unique ID of the object that was garbage collected.
        """
        safe_log(
            self.logger,
            logging.DEBUG,
            f"Active object {obj_id} was garbage collected unexpectedly.",
        )

        try:
            self.untrack_active_object(obj_id)
        except (KeyError, RuntimeError, ValueError) as e:
            safe_log(self.logger, logging.WARNING, f"Error in weakref cleanup: {e}")

    def clear_all(self) -> int:
        """
        Clears all active object tracking information. This effectively stops monitoring
        any currently active objects.

        Returns:
            int: The number of objects that were being tracked before clearing.
        """
        with self._lock:
            count = len(self._active_objects_count)
            self._active_objects_count.clear()
            self._active_objects_count_info.clear()
            return count

    def get_basic_stats(self) -> Dict[str, Any]:
        """
        Provides a summary of the active objects manager's statistics.

        Returns:
            Dict[str, Any]: A dictionary containing:
                - 'total_tracked': Total number of objects ever tracked (including dead refs).
                - 'living_objects': Number of objects still actively referenced by the application.
                - 'dead_weakrefs': Number of objects that have been garbage collected but whose
                                   weak references haven't been fully cleaned up yet.
                - 'total_memory_bytes': Total estimated memory of living objects.
                - 'next_id': The next available unique ID for tracking.
        """
        with self._lock:
            total_active = len(self._active_objects_count)
            living_active = self.get_active_count()
            dead_refs = total_active - living_active

            total_memory = sum(
                info.estimated_size for info in self.get_active_objects_count_info().values()
            )

            return {
                "total_tracked": total_active,
                "living_objects": living_active,
                "dead_weakrefs": dead_refs,
                "total_memory_bytes": total_memory,
                "next_id": self._next_id,
            }
